FRONT/src/components/RecipeCard/RecipeCard.jsx
FRONT/src/components/RecipeCard/RecipeCard.module.scss

Reestilizado de tarjetas verticales
Vista previa:

restyling vertical cardRecipe

---

FRONT/src/Redux/actions/index.js
FRONT/src/components/RecipeCard/RecipeCard.jsx
FRONT/src/components/RecipeCardHorizontal/RecipeCardHorizontal.module.css
FRONT/src/pages/RecipeDetail/RecipeDetail.jsx
FRONT/src/pages/RecipeDetail/RecipeDetail.module.scss

Recipe Detail funcionando Agregue ademas en Recipe Card Navlink para direccionar a Detail
Se modifico la action de detail para que renderice en el componente.

Recipe Detail Funcional

---

FRONT/package-lock.json
FRONT/package.json
FRONT/src/components/IngredientsList/ingredientsList.jsx
FRONT/src/pages/CreateRecipe/CreateRecipe.jsx

Estilice la lista de ingredientes ahora quedo mas limpia, deje el codigo viejo comentado por las dudas que haya afectado alguna funcionalidad, no lo creo pero por las dudas

Ingredients Lists Styling

---

FRONT/src/auth0-provider.js
FRONT/src/components/Auth0/login_button.js
FRONT/src/components/Auth0/logout_button.js
FRONT/src/components/NavBar/NavBar.jsx

Hola Chicos, agregué un boton en la Navbar, que es condicional respecto del estado de logueo. Login/Logout, y redirecciona al home una vez logueado o a la landing una vez deslogueado. Saludos!

Add conditional Login/Logout button to Navbar component

---

API/package-lock.json
API/package.json
API/src/app.js

Se agrego ruta de mercado pago para integracion

MercadoPagoIntegration Backend

---

FRONT/src/pages/Home/Home.jsx
FRONT/src/pages/RecipeDetail/RecipeDetail.jsx

Ahora el localStorage almacena el carrito segun el usuario este logueado o no.
Cuando ingresa nuevamente, chequea que el usuario invitado tenga un carrito en localStorage y cuando el usuario se loguea nuevamente, cheque que no tenga un carrito previo

localStorage save cart by user

---

API/src/controllers/postUser.js
API/src/models/Users.js
API/src/routes/index.js
API/src/routes/users.js

Se agrega EP de creación de usuarios

add POST User routes & controller

---

FRONT/src/Redux/actions/index.js
FRONT/src/Redux/reducer/index.js
FRONT/src/components/Filters/Filters.jsx
FRONT/src/pages/Home/Home.jsx

los filtros funcionan de manera combinada.
elegir dieta y luego ingredientes

filters combinated working

---

API/src/app.js
API/src/controllers/postCheckout.js
API/src/controllers/postPayment.js
API/src/controllers/postUser.js
API/src/routes/checkout.js
API/src/routes/index.js
API/src/routes/payment.js
FRONT/src/pages/ShoppingCart/ShoppingCart.jsx

Se termina el flujo del shopping cart. Se genera pedido y se abre ventana de pago

Feat client shopping cart

---

API/src/app.js
API/src/controllers/getRecipes.js
API/src/controllers/postCheckout.js
API/src/controllers/postPayment.js
API/src/controllers/postUser.js
API/src/helpers/modelsMock.js
API/src/models/Recipes.js
API/src/routes/checkout.js
API/src/routes/index.js
API/src/routes/payment.js
FRONT/src/pages/ShoppingCart/ShoppingCart.jsx

Se agregan Reviews, rating, idUsuario (creador), y precio total en GET /recipes y GET /recipes/id

Refact api/get recipe keys

---

FRONT/package.json
FRONT/src/Redux/actions/index.js
FRONT/src/Redux/reducer/index.js
FRONT/src/components/Filters/Filters.jsx
FRONT/src/pages/RecipeDetail/RecipeDetail.jsx

Se realiza filtro por precio y por rating relacionados a los demás filtros.

Filters For Price and Rating Completed

---

FRONT/src/Redux/reducer/index.js
FRONT/src/components/Filters/Filters.jsx

se modificaron dos lineas para que funcione todo ok!

Filters by price

---

FRONT/src/App.js

Se actualiza la url del back para que el front haga las peticiones a esa nueva URL

url back actualized

---

FRONT/src/auth0-provider.js

chicos, corregí la URL de derivación luego del logueo en Auth0. Ahora es la URL deployada. Cualquier cosa me avisan.
Saludos!

Hotfix Auth0 redirection on deployed URL

---

FRONT/src/auth0-provider.js

chicos, les hago el PR para que lo mergeen a main.

Hotfix-Auth0 redirection on deployed URL

---

FRONT/src/pages/RecipeDetail/RecipeDetail.jsx
FRONT/src/pages/ShoppingCart/ShoppingCart.jsx

Localstorage funcionando:
- componente home carga el carro desde localstorage
- recipedetail agrega los items a localstorage 
- shopingcart permite remover los items de localstorage. si el usuario recarga la pagina, obtiene los datos del carrito desde localstorage

Fix local storage cart

---

API/index.js
API/src/helpers/modelsMock.js
FRONT/src/Admin/Appmodel.js
FRONT/src/Admin/components/Reviews/Reviews.jsx
FRONT/src/Admin/components/ReviewsCard/ReviewsCard.jsx
FRONT/src/Admin/components/sideBar/SideBar.jsx
FRONT/src/Admin/components/sideBar/sideBar.css
FRONT/src/Admin/components/topBar/topBar.css
FRONT/src/Admin/pages/home/HomeAdmin.jsx
FRONT/src/Admin/pages/userList/UserList.jsx
FRONT/src/App.js
FRONT/src/Redux/actions/homeadmin.js
FRONT/src/Redux/actions/reviews.js
FRONT/src/Redux/reducer/homeadmin.js
FRONT/src/Redux/reducer/index.js
FRONT/src/Redux/reducer/reviews.js

visualizacion de componentes manejada desde el sideBar

DashBoard Admin

---

API/src/controllers/postUser.js

Se agrega la funcion sendEmail para que envie emails cuando un usuario se registra por primera vez

user get welcome email when register in db

---

API/src/helpers/modelsMock.js
FRONT/src/Redux/actions/reviews.js
FRONT/src/components/UserMenu/UserMenu.jsx
FRONT/src/pages/Home/Home.jsx

Solucionado los problemas con getReviews y getUsers

Fix problems

---

API/src/controllers/deleteReview.js
API/src/routes/reviews.js
FRONT/src/Redux/actions/reviews.js
FRONT/src/components/ReviewsBox/ReviewsBox.jsx
FRONT/src/components/ReviewsCard/ReviewsCard.jsx
FRONT/src/components/ReviewsCard/ReviewsCard.module.scss

Se terminó con el circuito para que el usuario pueda eliminar la review que ha realizado.
Solo puede agregar una review por receta y solo puede eliminar esa misma revew creada por el

Fix reviews recipe detail

---

API/src/controllers/getOrders.js
API/src/controllers/postOrder.js
API/src/controllers/postPayment.js
API/src/helpers/modelsMock.js
API/src/models/Orders.js

Controllers y models relacionados con la creación de la orden y el pago

shop & payment flow

---

FRONT/package-lock.json
FRONT/src/pages/Home/Home.jsx
FRONT/src/pages/RecipeDetail/RecipeDetail.jsx
FRONT/src/pages/ShoppingCart/ShoppingCart.jsx

Solucionado inconvenientes con localStorage
- Carga correcta de informacion del usuario
- Solucion al problema que duplicaba el ingrediente que se agregaba al localStorage
- Ahora el cambio de la cantidad del ingrediente en la vista de carrito tambien se guarda en localStorage.
- Verificado el funcionamiento cuando el usuario recarga la pagina en todas las vistas

Fix local storage

---

API/src/controllers/putReview.js
API/src/routes/reviews.js

Hola Chicos, Lo logré!!!! Les dejo una función desde el back para banear los reviews que tengan malos comentarios. Cambia la propiedad visible de true a false. Saludos!

Feat-API Function to ban reviews from users

---

API/src/controllers/deleteFavorite.js
API/src/controllers/postFavorite.js
API/src/routes/favorites.js
FRONT/src/Redux/actions/favorites.js
FRONT/src/Redux/reducer/favorites.js
FRONT/src/Redux/reducer/index.js
FRONT/src/pages/RecipeDetail/RecipeDetail.jsx
FRONT/src/pages/RecipeDetail/RecipeDetail.module.css

Se agrega un boton en el detalle de cada receta para que el usuario pueda agregar esa receta a sus favoritas.
El boton guarda la informacion en la tabla Favorites de la base de datos para que este disponible para toda la aplicacion

add button to favorite in RecipeDetail

---

FRONT/src/components/RecipesBox/RecipesBox.module.scss
FRONT/src/components/ReviewsCard/ReviewsCard.module.scss
FRONT/src/components/UserOrdersBox/UserOrdersBox.jsx
FRONT/src/components/UserOrdersBox/UserOrdersBox.module.scss
FRONT/src/components/UserReviewsBox/UserReviewsBox.jsx
FRONT/src/components/UserReviewsBox/UserReviewsBox.module.scss
FRONT/src/pages/userPage/UserPage.jsx
FRONT/src/pages/userPage/UserPage.module.css

Modificado el panel de usuario.
Agregados cuadros para ver sus favoritos, reviews, recetas creadas y ordenes

Feat user page

---

API/package-lock.json
FRONT/src/components/UserOrdersBox/UserOrdersBox.module.scss
FRONT/src/pages/userPage/UserPage.jsx
FRONT/src/pages/userPage/UserPage.module backup.css
FRONT/src/pages/userPage/UserPage.module.css
FRONT/src/pages/userPage/userPage-backup.jsx

Reestilizado de pagina de usuario

restyling in userPage

---

FRONT/src/pages/CreateRecipe/CreateRecipe.jsx

Hola Chicos, les dejo una versión responsive de la página Create Recipe.  Solo se modifica el archivo jsx. Saludos!!

Upgraded Create Recipe Page, responsiveStyle

---

FRONT/src/Admin/components/widgetLg/WidgetLg.jsx
FRONT/src/Admin/pages/home/HomeAdmin.jsx
FRONT/src/pages/Orders/Orders.js

Se vuelve para atras con el merge.

Revert "Admin"

---

FRONT/src/Admin/pages/home/HomeAdmin.jsx

ingredientsHome

---

FRONT/src/components/RecipeCard/RecipeCard.jsx
FRONT/src/components/RecipeCard/RecipeCard.module.scss
FRONT/src/pages/RecipeDetail/RecipeDetail.jsx
FRONT/src/pages/RecipeDetail/RecipeDetail.module.css

Se agrega una imagen por defecto cuando el usuario no carga una al momento de crearla

add a default image for created recipes in recipesCard & recipeDetail

---

FRONT/src/pages/ShoppingCart/ShoppingCart.jsx

shopcartdmode

---

FRONT/src/Redux/actions/users.js

fixed alert reset mail

---

FRONT/src/Admin/Appmodel.js
FRONT/src/Admin/components/UserRow/UserRow.jsx
FRONT/src/Redux/actions/users.js

fixed edith role
